export const D = {
bg:"#050507", card:"#111116", card2:"#161620",
border:"#1C1C28", text:"#EFEFFA", sub:"#52526A", sub2:"#28283A",
lime:"#C8FF00", red:"#FF4040", blue:"#3B9EFF", orange:"#FF8C00",
purple:"#A855F7", pink:"#F472B6", green:"#22C55E", teal:"#14B8A6"
};
export const F = { d:"'Syne',sans-serif", b:"'Inter',sans-serif", m:"'JetBrains Mono',monospace" };
export const GA: Record<string,string> = { mass:D.lime, cut:D.red, force:D.orange, fit:D.blue, tone:D.purple, teen:D.teal };
export const GG: Record<string,string> = { mass:"135deg,#C8FF00,#6A8800", cut:"135deg,#FF4040,#AA1010", force:"135deg,#FF8C00,#AA4400", fit:"135deg,#3B9EFF,#0055CC", tone:"135deg,#A855F7,#5010A0", teen:"135deg,#14B8A6,#087060" };

export const load = (k:string, d:any) => { try { return JSON.parse(localStorage.getItem(k)??'null')??d; } catch { return d; } };
export const save = (k:string, v:any) => { try { localStorage.setItem(k, JSON.stringify(v)); } catch {} };

export interface Exercise {
name:string; emoji:string; muscle:string; muscleGroup:string;
cat:"compound"|"isolation"|"bodyweight";
tempo:{d:number;h:number;u:number};
rest:number; sets:number; reps:string;
req:string[]; bodyweight:boolean;
why:string; tips:string[];
muscles_detail:string;
erreurs:string[];
conseil:string;
alternatives:string[];
}

export const EX: Record<string, Exercise> = {
bench:{name:"Développé couché barre",emoji:"🏋️",muscle:"Pectoraux",muscleGroup:"chest",cat:"compound",tempo:{d:3,h:1,u:2},rest:120,sets:4,reps:"6-8",req:["barbell","bench"],bodyweight:false,why:"Le mouvement roi de la poitrine. Stimule le grand pectoral sur toute sa longueur.",tips:["Omoplates serrées contre le banc","Coudes à 45°, pas à 90°","Barre descend jusqu'au bas du sternum"],muscles_detail:"Grand pectoral (chef sternal et claviculaire), deltoïde antérieur, triceps brachial",erreurs:["Coudes trop écartés à 90° — dangereux pour les épaules","Fesses qui décollent du banc","Descente trop rapide sans contrôle"],conseil:"Pince les omoplates et pousse les pieds dans le sol. Si tu n'arrives pas à 6 reps proprement, allège le poids.",alternatives:["dbBench","incline","pushup","dip","flyes"]},

incline:{name:"Développé incliné haltères",emoji:"📐",muscle:"Pectoraux haut",muscleGroup:"chest",cat:"compound",tempo:{d:3,h:1,u:2},rest:90,sets:3,reps:"8-10",req:["dumbbell","bench"],bodyweight:false,why:"Cible le chef claviculaire du grand pectoral. Donne le galbe supérieur de la poitrine.",tips:["Banc à 30° maximum","Rotation externe des haltères en haut","Coudes à 75° du corps"],muscles_detail:"Grand pectoral chef claviculaire, deltoïde antérieur, triceps",erreurs:["Banc trop incliné à plus de 45° — les épaules prennent tout","Coudes qui tombent vers l'intérieur","Amplitude trop réduite"],conseil:"30° est l'angle optimal. Au-delà de 45° tu travailles principalement les épaules, pas les pectoraux.",alternatives:["bench","dbBench","pushup","dip"]},

flyes:{name:"Écarté haltères couché",emoji:"🦅",muscle:"Pectoraux — isolation",muscleGroup:"chest",cat:"isolation",tempo:{d:3,h:2,u:2},rest:60,sets:3,reps:"12-15",req:["dumbbell","bench"],bodyweight:false,why:"Isolation parfaite du grand pectoral. Étirement maximal des fibres musculaires.",tips:["Légère flexion des coudes fixe","Descends jusqu'à sentir l'étirement","Remonte en arc de cercle"],muscles_detail:"Grand pectoral uniquement — isolation pure, coracobrachial",erreurs:["Bras trop tendus — risque pour les coudes","Descendre trop bas au-delà de 90°","Trop de charge, on perd l'étirement"],conseil:"Le poids doit être léger. On cherche l'étirement et la contraction, pas la charge maximale.",alternatives:["bench","dbBench","incline","dip"]},

dip:{name:"Dips pectoraux",emoji:"🔱",muscle:"Pecs bas · Triceps",muscleGroup:"chest",cat:"bodyweight",tempo:{d:3,h:1,u:2},rest:90,sets:3,reps:"8-12",req:["dip_bar"],bodyweight:true,why:"Excellent pour le bas des pectoraux et les triceps. Charge le corps entier.",tips:["Penche le buste 30° en avant pour cibler les pecs","Coudes légèrement écartés","Descends jusqu'à 90° de flexion"],muscles_detail:"Grand pectoral chef sternal inférieur, triceps brachial, deltoïde antérieur",erreurs:["Buste trop droit — les triceps dominent alors","Descente insuffisante — pas d'étirement","Épaules qui remontent vers les oreilles"],conseil:"Si tu arrives à 12 reps facilement, ajoute du lest avec une ceinture de musculation.",alternatives:["bench","pushup","diamondPushup","flyes"]},

skullcrush:{name:"Skull Crusher barre",emoji:"💀",muscle:"Triceps — chef long",muscleGroup:"triceps",cat:"compound",tempo:{d:3,h:1,u:2},rest:75,sets:3,reps:"8-10",req:["barbell","bench"],bodyweight:false,why:"Meilleur exercice pour le chef long du triceps. Donne la masse et l'épaisseur au bras.",tips:["Coudes pointés vers le plafond, immobiles","Descends la barre légèrement derrière la tête","Extension complète en haut"],muscles_detail:"Triceps brachial — chef long principalement, chef médial",erreurs:["Coudes qui s'écartent pendant le mouvement","Descendre vers le front plutôt que derrière la tête","Trop de poids — douleur aux coudes"],conseil:"Commence léger et maîtrise le mouvement. Le chef long s'étire seulement si la barre passe derrière la tête.",alternatives:["triceppush","overheadExt","diamondPushup","dip"]},

triceppush:{name:"Pushdown câble",emoji:"🔩",muscle:"Triceps — chef latéral",muscleGroup:"triceps",cat:"isolation",tempo:{d:3,h:1,u:2},rest:60,sets:3,reps:"12-15",req:["cables"],bodyweight:false,why:"Isolation parfaite du chef latéral. Donne le galbe visible du triceps de côté.",tips:["Coudes fixes contre le corps du début à la fin","Extension complète et verrou en bas","Pause 1s en bas avec contraction"],muscles_detail:"Triceps brachial — chef latéral et médial en contraction",erreurs:["Coudes qui s'écartent en poussant","Pencher le corps entier pour aider","Ne pas verrouiller complètement en bas"],conseil:"Varie entre corde et barre droite pour stimuler les chefs différemment selon les séances.",alternatives:["skullcrush","overheadExt","diamondPushup","dip"]},

overheadExt:{name:"Extension nuque haltère",emoji:"💪",muscle:"Triceps — chef long",muscleGroup:"triceps",cat:"isolation",tempo:{d:3,h:1,u:2},rest:60,sets:3,reps:"12-15",req:["dumbbell"],bodyweight:false,why:"Étirement maximal du chef long du triceps en position haute. Complémentaire au Pushdown.",tips:["Coudes proches des oreilles, immobiles","Descente lente derrière la nuque","Extension complète en haut"],muscles_detail:"Triceps brachial — chef long en étirement maximal",erreurs:["Coudes qui s'écartent lors de la descente","Mouvement involontaire des épaules","Poids trop lourd — perte de contrôle"],conseil:"Utilise un seul haltère tenu à deux mains pour plus de stabilité et de contrôle.",alternatives:["skullcrush","triceppush","diamondPushup"]},

deadlift:{name:"Soulevé de terre",emoji:"⚡",muscle:"Dos complet",muscleGroup:"back",cat:"compound",tempo:{d:3,h:0,u:2},rest:180,sets:4,reps:"5-6",req:["barbell"],bodyweight:false,why:"Le roi de tous les exercices. Sollicite environ 70% des muscles du corps en un seul mouvement.",tips:["DOS ABSOLUMENT PLAT — priorité absolue","Barre collée contre les tibias tout le long","Pousse le sol vers le bas plutôt que de tirer la barre"],muscles_detail:"Érecteurs du rachis, grand dorsal, trapèzes, ischio-jambiers, grand fessier, quadriceps",erreurs:["Dos arrondi — danger grave pour les lombaires","Barre qui s'éloigne du corps en montant","Genoux qui rentrent vers l'intérieur"],conseil:"Jamais d'ego lifting sur cet exercice. Un dos arrondi sous charge peut causer des hernies discales.",alternatives:["rdl","row","dbRow","legpress"]},

pullup:{name:"Tractions prise large",emoji:"🎯",muscle:"Grand dorsal",muscleGroup:"back",cat:"compound",tempo:{d:3,h:1,u:2},rest:90,sets:4,reps:"6-10",req:["pullupbar"],bodyweight:true,why:"L'exercice numéro 1 pour la largeur du dos. Développe le V-taper inégalable.",tips:["Initie le mouvement avec les omoplates qui descendent","Tire les coudes vers les hanches, pas vers l'arrière","Descends complètement entre chaque rep"],muscles_detail:"Grand dorsal, biceps brachial, rhomboïdes, trapèze moyen et inférieur, grand rond",erreurs:["Balancement du corps pour prendre de l'élan","Ne pas descendre complètement — amplitude incomplète","Menton seulement au niveau de la barre — monte plus haut"],conseil:"Si tu ne peux pas faire 6 reps, utilise un élastique de résistance ou commence par les tractions australiennes.",alternatives:["latpull","australianRow","dbRow","row"]},

row:{name:"Rowing barre",emoji:"🌊",muscle:"Dos épais",muscleGroup:"back",cat:"compound",tempo:{d:3,h:1,u:2},rest:90,sets:4,reps:"6-8",req:["barbell"],bodyweight:false,why:"Le développé couché du dos. Construit l'épaisseur et la densité musculaire du dos.",tips:["Buste à 45° — ni vertical ni horizontal","Tire la barre vers le nombril","Pince les omoplates en fin de mouvement"],muscles_detail:"Grand dorsal, rhomboïdes, trapèzes moyen et inférieur, biceps, deltoïde postérieur",erreurs:["Dos arrondi sous la charge","Trop d'élan avec le dos pour aider","Tirer trop haut vers la poitrine plutôt que le nombril"],conseil:"Imagine que tes bras sont des crochets passifs — c'est le dos qui fait le travail, pas les biceps.",alternatives:["dbRow","latpull","pullup","australianRow","deadlift"]},

latpull:{name:"Tirage vertical poulie",emoji:"⛵",muscle:"Grand dorsal",muscleGroup:"back",cat:"compound",tempo:{d:3,h:1,u:2},rest:75,sets:3,reps:"10-12",req:["cables"],bodyweight:false,why:"Excellent pour la largeur du dos quand les tractions sont encore trop difficiles.",tips:["Tire vers le sternum, pas le menton","Penche légèrement le buste en arrière","Contrôle la remontée lentement"],muscles_detail:"Grand dorsal, biceps brachial, rhomboïdes, grand rond",erreurs:["Tirer derrière la nuque — très dangereux pour les cervicales","Trop d'élan avec le corps","Prise trop large qui réduit l'amplitude"],conseil:"Prise large pour la largeur du dos, prise neutre pour plus d'activation du grand dorsal.",alternatives:["pullup","australianRow","row","dbRow"]},

curl:{name:"Curl barre",emoji:"💥",muscle:"Biceps",muscleGroup:"biceps",cat:"compound",tempo:{d:3,h:1,u:2},rest:75,sets:3,reps:"8-10",req:["barbell"],bodyweight:false,why:"Le classique absolu du biceps. Permet la charge maximale possible sur le biceps.",tips:["Coudes FIXES contre le corps — ne bougent pas","Supine la prise en haut pour la contraction max","Descente lente et contrôlée en 3 secondes"],muscles_detail:"Biceps brachial (long et court chef), brachial antérieur, supinateur",erreurs:["Élan avec le dos — les lombaires compensent","Coudes qui avancent en montant","Pas d'extension complète en bas"],conseil:"La descente lente de 3 secondes est plus efficace que la montée pour la croissance musculaire.",alternatives:["dbCurl","hammercurl","australianRow"]},

dbCurl:{name:"Curl haltères alterné",emoji:"💥",muscle:"Biceps",muscleGroup:"biceps",cat:"compound",tempo:{d:3,h:1,u:2},rest:60,sets:3,reps:"10-12",req:["dumbbell"],bodyweight:false,why:"La rotation de supination maximise la contraction du biceps à chaque répétition.",tips:["Tourne le poignet vers l'extérieur en montant","Coudes absolument fixes contre le corps","Pause 1s en haut avec contraction maximale"],muscles_detail:"Biceps brachial long et court chef, brachial antérieur",erreurs:["Pas de rotation de supination — perd l'avantage des haltères","Alterner trop vite — perd le contrôle","Balancement du corps pour aider"],conseil:"Fais une pause d'1 seconde en haut avec contraction maximale pour chaque bras.",alternatives:["curl","hammercurl","australianRow"]},

hammercurl:{name:"Curl marteau",emoji:"🔨",muscle:"Brachial antérieur",muscleGroup:"biceps",cat:"compound",tempo:{d:3,h:1,u:2},rest:60,sets:3,reps:"10-12",req:["dumbbell"],bodyweight:false,why:"Développe le brachial antérieur, muscle situé sous le biceps qui le pousse vers le haut et augmente le périmètre du bras.",tips:["Prise neutre — pouce vers le haut du début à la fin","Mouvement strict sans rotation du poignet","Coudes fixes contre le corps"],muscles_detail:"Brachial antérieur, brachio-radial, biceps brachial chef long",erreurs:["Tourner le poignet en montant — ça devient un curl normal","Coudes qui avancent pour aider","Élan avec le dos"],conseil:"Le brachial antérieur est souvent sous-développé. En l'épaississant, tu augmentes le tour de bras même sans plus de biceps.",alternatives:["curl","dbCurl","australianRow"]},

ohp:{name:"Développé militaire barre",emoji:"🔥",muscle:"Épaules — ant.",muscleGroup:"shoulders",cat:"compound",tempo:{d:3,h:1,u:2},rest:120,sets:4,reps:"6-8",req:["barbell"],bodyweight:false,why:"Le roi des épaules. Sollicite les 3 faisceaux du deltoïde et les triceps en mouvement fonctionnel.",tips:["Gainage abdominal très fort pendant tout le mouvement","Coudes légèrement en avant de la barre en bas","Passe la tête en avant quand la barre dépasse le front"],muscles_detail:"Deltoïde antérieur, latéral et postérieur, triceps brachial, trapèzes supérieurs",erreurs:["Cambrer excessivement le bas du dos — lombaires en danger","Tête qui part en avant sans que la barre suive","Manque de gainage — perte d'énergie"],conseil:"Debout est plus difficile mais plus complet qu'assis. Engage les fessiers et le core avant de presser.",alternatives:["dbOhp","lateral","frontRaise","facePull"]},

dbOhp:{name:"Développé épaules haltères",emoji:"🔥",muscle:"Épaules",muscleGroup:"shoulders",cat:"compound",tempo:{d:3,h:1,u:2},rest:90,sets:3,reps:"8-10",req:["dumbbell"],bodyweight:false,why:"Plus de liberté de mouvement que la barre. Active mieux les muscles stabilisateurs des épaules.",tips:["Position en W à 90° en bas","Rotation externe des haltères en haut","Gainage du tronc maintenu"],muscles_detail:"Deltoïde antérieur et latéral, triceps brachial, trapèzes supérieurs, stabilisateurs",erreurs:["Coudes trop en avant en bas — mauvais placement","Pas de rotation des haltères en montant","Bas du dos qui creuse"],conseil:"Idéal si tu as des douleurs aux épaules avec la barre. La liberté de mouvement protège les articulations.",alternatives:["ohp","lateral","facePull","frontRaise"]},

lateral:{name:"Élévations latérales",emoji:"🕊️",muscle:"Épaules — lat.",muscleGroup:"shoulders",cat:"isolation",tempo:{d:3,h:1,u:2},rest:60,sets:4,reps:"12-15",req:["dumbbell"],bodyweight:false,why:"L'exercice indispensable pour la largeur des épaules. Aucun autre mouvement ne cible aussi bien le deltoïde latéral.",tips:["Monte jusqu'à l'horizontale seulement — pas plus haut","Pouce légèrement vers le bas pour mieux isoler","Pas d'élan avec le corps"],muscles_detail:"Deltoïde latéral — isolation pure et ciblée",erreurs:["Monter au-dessus de l'épaule — les trapèzes prennent le relais","Trop d'élan avec le corps — perd le bénéfice","Coudes trop fléchis — réduit la résistance"],conseil:"Poids très léger. 5 à 8 kg suffisent pour la plupart des gens. La qualité d'exécution prime sur la charge.",alternatives:["cableLateral","ohp","dbOhp","facePull"]},

cableLateral:{name:"Élévations latérales câble",emoji:"🔌",muscle:"Épaules — lat.",muscleGroup:"shoulders",cat:"isolation",tempo:{d:3,h:1,u:2},rest:60,sets:3,reps:"15-20",req:["cables"],bodyweight:false,why:"La poulie maintient une tension constante contrairement aux haltères qui perdent de la résistance en bas.",tips:["Tension constante du début à la fin","Monte à hauteur d'épaule","Contrôle la descente"],muscles_detail:"Deltoïde latéral, sus-épineux",erreurs:["Poulie trop haute — perd la tension en bas","Élan avec le corps","Trop de charge"],conseil:"La résistance constante du câble est supérieure aux haltères pour l'isolation du deltoïde latéral.",alternatives:["lateral","ohp","dbOhp"]},

rearDelt:{name:"Oiseau — faisceau postérieur",emoji:"🦅",muscle:"Épaules — post.",muscleGroup:"shoulders",cat:"isolation",tempo:{d:3,h:1,u:2},rest:60,sets:3,reps:"12-15",req:["dumbbell"],bodyweight:false,why:"Le faisceau postérieur est presque toujours négligé. Crucial pour l'équilibre musculaire et la santé à long terme.",tips:["Buste parallèle au sol — vraiment horizontal","Coudes légèrement fléchis et fixes","Pince les omoplates en haut du mouvement"],muscles_detail:"Deltoïde postérieur, rhomboïdes, trapèze moyen",erreurs:["Buste pas assez penché — les trapèzes compensent","Élan avec le corps — perd l'isolation","Pas de contraction en haut"],conseil:"Fais-le en fin de séance. Un deltoïde postérieur fort prévient la majorité des blessures chroniques d'épaule.",alternatives:["facePull","lateral","cableLateral"]},

facePull:{name:"Face Pull câble",emoji:"🎯",muscle:"Épaules post. · Rotateurs",muscleGroup:"shoulders",cat:"compound",tempo:{d:3,h:2,u:2},rest:60,sets:3,reps:"15-20",req:["cables"],bodyweight:false,why:"Indispensable pour la santé des épaules. Renforce la coiffe des rotateurs et corrige les déséquilibres musculaires.",tips:["Rotation externe maximale en tirant","Coudes à hauteur d'épaule ou plus haut","Tire vers le visage, pas le menton"],muscles_detail:"Deltoïde postérieur, sus-épineux, infra-épineux, rhomboïdes, trapèze",erreurs:["Rotation externe insuffisante — perd le bénéfice principal","Trop de poids — perd le contrôle","Coudes qui descendent sous les épaules"],conseil:"À faire chaque séance si possible. C'est un exercice de santé autant que de performance.",alternatives:["rearDelt","lateral","cableLateral"]},

frontRaise:{name:"Élévations frontales",emoji:"⬆️",muscle:"Épaules — ant.",muscleGroup:"shoulders",cat:"isolation",tempo:{d:3,h:1,u:2},rest:60,sets:3,reps:"12-15",req:["dumbbell"],bodyweight:false,why:"Isole le faisceau antérieur du deltoïde, déjà sollicité dans tous les développés.",tips:["Hauteur d'épaule maximum — pas plus","Pas d'élan du corps","Descente contrôlée"],muscles_detail:"Deltoïde antérieur, grand pectoral chef claviculaire",erreurs:["Monter trop haut au-dessus des épaules","Élan avec le dos ou les genoux","Trop lourd — perd le contrôle"],conseil:"Le deltoïde antérieur est déjà très sollicité dans les développés. Poids léger et exécution stricte.",alternatives:["ohp","dbOhp","lateral"]},

squat:{name:"Squat barre",emoji:"🦵",muscle:"Quadriceps · Fessiers",muscleGroup:"legs",cat:"compound",tempo:{d:3,h:1,u:2},rest:180,sets:4,reps:"6-8",req:["barbell"],bodyweight:false,why:"Le roi des exercices de jambes. Sollicite quadriceps, fessiers, ischio-jambiers, dos et stabilisateurs.",tips:["Genoux dans l'axe des orteils — ne rentrent pas","Descends jusqu'au parallèle minimum — cuisses horizontales","Dos parfaitement droit, barre sur les trapèzes"],muscles_detail:"Quadriceps, grand fessier, ischio-jambiers, mollets, érecteurs du rachis, stabilisateurs",erreurs:["Genoux qui rentrent vers l'intérieur lors de la montée","Dos qui arrondit sous la charge","Pas assez profond — amplitude insuffisante"],conseil:"La profondeur est la clé. Mieux vaut moins lourd et descendre profond que lourd et partiel.",alternatives:["gobletSquat","legpress","bwSquat","lunge","rdl"]},

legpress:{name:"Presse à cuisses",emoji:"🦿",muscle:"Quadriceps · Fessiers",muscleGroup:"legs",cat:"compound",tempo:{d:3,h:1,u:2},rest:90,sets:4,reps:"10-12",req:["machines"],bodyweight:false,why:"Permet de surcharger les jambes en toute sécurité pour le dos. Excellent complément au squat.",tips:["Pieds à largeur d'épaules","Ne verrouille jamais les genoux en extension","Amplitude complète sans décoller les fesses"],muscles_detail:"Quadriceps, grand fessier, ischio-jambiers selon la position des pieds",erreurs:["Genoux qui rentrent lors de la poussée","Fesses qui décollent du siège — lombaires en danger","Amplitude trop courte — manque d'efficacité"],conseil:"Pieds hauts sur la plateforme = plus de fessiers. Pieds bas = plus de quadriceps. Joue avec la position.",alternatives:["squat","gobletSquat","bwSquat","lunge"]},

rdl:{name:"Soulevé jambes tendues",emoji:"🎖️",muscle:"Ischio-jambiers",muscleGroup:"legs",cat:"compound",tempo:{d:3,h:1,u:2},rest:90,sets:3,reps:"10-12",req:["barbell"],bodyweight:false,why:"Le meilleur exercice pour les ischio-jambiers. Combine étirement profond et contraction en position raccourcie.",tips:["DOS ABSOLUMENT PLAT — priorité numéro 1","Descends jusqu'à sentir l'étirement dans les ischio","Barre reste proche du corps tout le long"],muscles_detail:"Ischio-jambiers, grand fessier, érecteurs du rachis",erreurs:["Dos arrondi sous la charge — très dangereux pour les lombaires","Genoux trop fléchis — ressemble à un soulevé de terre classique","Barre qui s'éloigne du corps lors de la descente"],conseil:"Jamais de charge lourde si le dos n'est pas parfaitement plat. Sens l'étirement en bas avant de remonter.",alternatives:["legcurl","deadlift","squat","lunge"]},

lunge:{name:"Fentes marchées",emoji:"⚔️",muscle:"Quadriceps · Fessiers",muscleGroup:"legs",cat:"bodyweight",tempo:{d:3,h:0,u:2},rest:75,sets:3,reps:"10/côté",req:[],bodyweight:true,why:"Corrige les déséquilibres entre les deux jambes. Le travail unilatéral révèle les faiblesses cachées.",tips:["Grand pas — le genou arrière descend près du sol","Torse droit et vertical pendant tout le mouvement","Genou avant dans l'axe des orteils"],muscles_detail:"Quadriceps, grand fessier, ischio-jambiers, stabilisateurs de la cheville et du genou",erreurs:["Pas trop court — le genou arrière ne descend pas assez","Torse qui penche vers l'avant","Genou avant qui part en valgus"],conseil:"Commence sans poids pour maîtriser l'équilibre, puis ajoute des haltères de chaque côté.",alternatives:["squat","gobletSquat","bwSquat","legpress","rdl"]},

legcurl:{name:"Leg Curl couché",emoji:"🦵",muscle:"Ischio-jambiers",muscleGroup:"legs",cat:"isolation",tempo:{d:3,h:2,u:2},rest:60,sets:3,reps:"12-15",req:["machines"],bodyweight:false,why:"Isolation complète des ischio-jambiers en contraction concentrique. Complémentaire au soulevé de terre.",tips:["Contraction maximale en haut — tiens 2 secondes","Descente lente et contrôlée","Hanches plaquées sur le coussin"],muscles_detail:"Ischio-jambiers (biceps fémoral, semi-tendineux, semi-membraneux), gastrocnémien",erreurs:["Hanches qui se soulèvent pour aider — perd l'isolation","Amplitude insuffisante — pas de contraction complète","Trop vite — perd le bénéfice excentrique"],conseil:"Tiens 2 secondes en contraction maximale à chaque répétition pour plus d'efficacité.",alternatives:["rdl","deadlift","lunge"]},

calf:{name:"Mollets machine",emoji:"🏃",muscle:"Mollets",muscleGroup:"legs",cat:"isolation",tempo:{d:3,h:2,u:2},rest:45,sets:4,reps:"15-20",req:["machines"],bodyweight:false,why:"Les mollets sont des muscles posturaux très endurants qui nécessitent du volume élevé pour progresser.",tips:["Amplitude maximale — descends complètement en bas","Pause de 1 seconde en contraction maximale en haut","Contrôle la descente lentement"],muscles_detail:"Gastrocnémien (visible de l'extérieur), soléaire (sous le gastrocnémien)",erreurs:["Amplitude trop courte — pas d'étirement complet en bas","Rebond en bas sans contrôle — perd le bénéfice excentrique","Trop vite"],conseil:"Les mollets récupèrent très vite. Tu peux les travailler 3 à 4 fois par semaine sans problème.",alternatives:["bwCalf"]},

bwCalf:{name:"Mollets poids du corps",emoji:"🏃",muscle:"Mollets",muscleGroup:"legs",cat:"isolation",tempo:{d:3,h:2,u:2},rest:45,sets:4,reps:"25-30",req:[],bodyweight:true,why:"Sans matériel et tout aussi efficace avec suffisamment de volume et d'amplitude.",tips:["Fais-le sur le bord d'une marche pour plus d'amplitude","Pause de 1 seconde en haut","Descends complètement en bas pour l'étirement"],muscles_detail:"Gastrocnémien, soléaire",erreurs:["Trop vite — perd le contrôle et l'amplitude","Amplitude insuffisante sans marche","Rebond en bas"],conseil:"Le bord d'une marche ou d'une boîte augmente énormément l'efficacité en doublant l'amplitude.",alternatives:["calf"]},

pushup:{name:"Pompes classiques",emoji:"✊",muscle:"Pectoraux · Triceps",muscleGroup:"chest",cat:"bodyweight",tempo:{d:3,h:1,u:2},rest:60,sets:4,reps:"12-20",req:[],bodyweight:true,why:"Le fondamental absolu de la musculation. Efficace partout, sans aucun matériel.",tips:["Corps parfaitement aligné de la tête aux talons","Coudes à 45° du corps — pas à 90°","Descends jusqu'à 1cm du sol"],muscles_detail:"Grand pectoral, triceps brachial, deltoïde antérieur, stabilisateurs du core",erreurs:["Hanches qui s'affaissent — signe de manque de gainage","Coudes trop écartés à 90° — mauvais pour les épaules","Amplitude insuffisante — pas d'étirement"],conseil:"Trop facile ? Surélève les pieds. Trop difficile ? Pose les genoux au sol.",alternatives:["bench","dbBench","dip","diamondPushup","incline"]},

diamondPushup:{name:"Pompes diamant",emoji:"💎",muscle:"Triceps",muscleGroup:"triceps",cat:"bodyweight",tempo:{d:3,h:1,u:2},rest:60,sets:3,reps:"10-15",req:[],bodyweight:true,why:"Maximum de triceps sans aucun matériel. Idéal pour finir une séance ou s'entraîner à la maison.",tips:["Forme un triangle avec le pouce et l'index","Coudes restent proches du corps tout le mouvement","Extension complète en haut"],muscles_detail:"Triceps brachial tous les chefs, grand pectoral chef sternal",erreurs:["Coudes qui s'écartent — perd le focus triceps","Hanches qui se soulèvent pour compenser","Amplitude insuffisante"],conseil:"Si trop difficile, commence avec les genoux au sol. Si trop facile, surélève les pieds.",alternatives:["triceppush","skullcrush","overheadExt","dip"]},

australianRow:{name:"Traction australienne",emoji:"🌊",muscle:"Dos moyen",muscleGroup:"back",cat:"compound",tempo:{d:3,h:1,u:2},rest:75,sets:3,reps:"10-15",req:["pullupbar"],bodyweight:true,why:"Idéal pour progresser vers les vraies tractions. Travaille le dos moyen sans aucun équipement lourd.",tips:["Corps en planche rigide — ne plie pas","Tire les coudes vers les hanches","Poitrine touche la barre en haut"],muscles_detail:"Grand dorsal, rhomboïdes, trapèze moyen, biceps, deltoïde postérieur",erreurs:["Hanches qui s'affaissent — corps pas gainé","Amplitude insuffisante — ne monte pas assez","Corps trop vertical — trop facile"],conseil:"Plus tu inclines le corps horizontalement, plus c'est difficile. Progresse vers les tractions complètes.",alternatives:["pullup","latpull","row","dbRow"]},

dbRow:{name:"Rowing haltère unilatéral",emoji:"🌊",muscle:"Dos",muscleGroup:"back",cat:"compound",tempo:{d:3,h:1,u:2},rest:75,sets:3,reps:"10-12",req:["dumbbell"],bodyweight:false,why:"Corrige les déséquilibres entre les deux côtés du dos. Grande amplitude de mouvement possible.",tips:["Genou et main du même côté sur le banc","Tire le coude vers le plafond","Dos parallèle au sol"],muscles_detail:"Grand dorsal, rhomboïdes, trapèze moyen, biceps brachial",erreurs:["Rotation du buste pour aider — perd l'isolation","Élan avec le corps","Coude qui part trop latéralement"],conseil:"Tire le coude vers le plafond et pas vers l'arrière pour maximiser l'activation du grand dorsal.",alternatives:["row","pullup","latpull","australianRow"]},

gobletSquat:{name:"Goblet Squat",emoji:"🦵",muscle:"Quadriceps",muscleGroup:"legs",cat:"compound",tempo:{d:3,h:1,u:2},rest:90,sets:3,reps:"12-15",req:["dumbbell"],bodyweight:false,why:"Parfait pour apprendre la technique du squat. Très accessible et sécurisé pour débuter.",tips:["Haltère contre la poitrine — ne tombe pas en avant","Descends profond — coudes entre les genoux en bas","Dos droit tout le mouvement"],muscles_detail:"Quadriceps, grand fessier, ischio-jambiers, stabilisateurs du genou",erreurs:["Haltère qui tombe vers l'avant — brise la posture","Dos arrondi en bas — lombaires en danger","Genoux en valgus lors de la remontée"],conseil:"Idéal en échauffement avant le squat barre. Descends profondément pour ouvrir les hanches.",alternatives:["squat","bwSquat","legpress","lunge"]},

bwSquat:{name:"Squat poids du corps",emoji:"🦵",muscle:"Quadriceps",muscleGroup:"legs",cat:"bodyweight",tempo:{d:3,h:1,u:2},rest:60,sets:4,reps:"20-25",req:[],bodyweight:true,why:"Le fondamental des jambes sans matériel. Accessible à tous, partout.",tips:["Genoux dans l'axe des orteils","Descends le plus profond possible","Bras tendus devant pour l'équilibre"],muscles_detail:"Quadriceps, grand fessier, ischio-jambiers, stabilisateurs",erreurs:["Genoux en valgus — rentrent vers l'intérieur","Talons qui décollent du sol","Tronc trop incliné en avant"],conseil:"Pour progresser, ajoute des pauses de 3 secondes en bas. Quand trop facile, passe au goblet squat.",alternatives:["gobletSquat","squat","lunge","legpress"]},

hipThrust:{name:"Hip Thrust barre",emoji:"🍑",muscle:"Grand fessier",muscleGroup:"glutes",cat:"compound",tempo:{d:2,h:2,u:2},rest:90,sets:4,reps:"10-12",req:["barbell","bench"],bodyweight:false,why:"Le meilleur exercice biomécanique pour les fessiers. Activation maximale du grand fessier prouvée.",tips:["Contracte les fessiers au maximum pendant 2 secondes en haut","Pousse avec les talons — pas la pointe des pieds","Menton légèrement rentré pour protéger les lombaires"],muscles_detail:"Grand fessier (activation maximale), ischio-jambiers, adducteurs",erreurs:["Extension lombaire excessive en haut — lombaires qui compensent","Pas de contraction isométrique en haut","Pieds trop proches des fesses — quadriceps qui dominent"],conseil:"La contraction de 2 secondes en position haute est la clé de l'efficacité de cet exercice.",alternatives:["bwHipThrust","gluteBridge","sumoSquat","squat"]},

bwHipThrust:{name:"Hip Thrust sol",emoji:"🍑",muscle:"Grand fessier",muscleGroup:"glutes",cat:"bodyweight",tempo:{d:2,h:2,u:2},rest:60,sets:4,reps:"15-20",req:[],bodyweight:true,why:"Version sans matériel très efficace. Excellent pour activer et développer les fessiers.",tips:["Pousse avec les talons — pieds à plat","Contracte fort 2 secondes en haut","Genoux à 90° en position haute"],muscles_detail:"Grand fessier, ischio-jambiers, stabilisateurs du bassin",erreurs:["Lombaires qui compensent — extension du bas du dos excessive","Pieds trop proches des fesses — quadriceps dominent","Pas de contraction maintenue en haut"],conseil:"Ajoute une bande élastique autour des genoux pour plus de résistance et activer les abducteurs.",alternatives:["hipThrust","gluteBridge","sumoSquat"]},

gluteBridge:{name:"Pont Fessier",emoji:"🍑",muscle:"Grand fessier",muscleGroup:"glutes",cat:"bodyweight",tempo:{d:2,h:2,u:2},rest:45,sets:3,reps:"15-20",req:[],bodyweight:true,why:"Activation parfaite des fessiers en douceur. Idéal en échauffement avant les squats.",tips:["Pieds à plat, genoux à 90°","Contracte les fessiers fort en haut","Dos plat sur le sol"],muscles_detail:"Grand fessier, ischio-jambiers, stabilisateurs lombaires",erreurs:["Extension lombaire trop forte — dos qui se cambre","Pas de contraction des fessiers en haut","Pieds trop loin — ischio-jambiers dominent"],conseil:"Parfait en échauffement avant squats et fentes. Ajoute une bande élastique pour progresser.",alternatives:["hipThrust","bwHipThrust","sumoSquat"]},

sumoSquat:{name:"Squat Sumo haltère",emoji:"🦵",muscle:"Fessiers · Adducteurs",muscleGroup:"glutes",cat:"compound",tempo:{d:3,h:1,u:2},rest:90,sets:3,reps:"12-15",req:["dumbbell"],bodyweight:false,why:"Cible spécifiquement les fessiers et les adducteurs grâce à l'écartement large des pieds.",tips:["Pieds plus larges que les épaules, orteils à 45°","Pousse les genoux vers l'extérieur en descendant","Haltère entre les jambes"],muscles_detail:"Grand fessier, adducteurs, quadriceps, ischio-jambiers",erreurs:["Genoux en valgus qui rentrent vers l'intérieur","Tronc trop incliné en avant","Pas assez d'écartement des pieds"],conseil:"En descendant, pousse activement les genoux vers l'extérieur pour maximiser l'activation des fessiers.",alternatives:["hipThrust","bwHipThrust","gluteBridge","squat"]},

plank:{name:"Gainage frontal",emoji:"🧱",muscle:"Transverse · Core",muscleGroup:"abs",cat:"bodyweight",tempo:{d:0,h:0,u:0},rest:45,sets:3,reps:"45-60 sec",req:[],bodyweight:true,why:"Le gainage profond protège la colonne vertébrale. Indispensable comme base pour tous les autres exercices.",tips:["Corps parfaitement aligné de la tête aux talons","Rentre le nombril vers la colonne","Respire normalement — ne bloque pas"],muscles_detail:"Transverse de l'abdomen, obliques, érecteurs du rachis, fessiers, épaules",erreurs:["Hanches trop hautes — forme une pyramide","Hanches qui s'affaissent — lombaires en danger","Apnée complète — contre-productive"],conseil:"Mieux vaut 30 secondes en position parfaite que 60 secondes en mauvaise position.",alternatives:["sidePlank","hollowBody","mountainClimber","crunch"]},

crunch:{name:"Crunch classique",emoji:"🎯",muscle:"Grand droit — haut",muscleGroup:"abs",cat:"bodyweight",tempo:{d:2,h:1,u:2},rest:45,sets:3,reps:"15-20",req:[],bodyweight:true,why:"Isolation de la partie haute du grand droit de l'abdomen. Efficace et accessible.",tips:["Expire en contractant lors de la montée","Lombaires collés au sol","Regard vers le plafond — pas vers les genoux"],muscles_detail:"Grand droit de l'abdomen partie supérieure, obliques comme stabilisateurs",erreurs:["Tirer sur la nuque avec les mains — cervicales en danger","Lombaires qui décollent du sol","Trop d'amplitude — assis complet ne sert à rien"],conseil:"L'amplitude est intentionnellement courte. Ce qui compte c'est la contraction des abdos, pas la hauteur.",alternatives:["legRaise","plank","russianTwist","hollowBody"]},

legRaise:{name:"Élévations de jambes",emoji:"🦵",muscle:"Grand droit — bas",muscleGroup:"abs",cat:"bodyweight",tempo:{d:3,h:1,u:2},rest:45,sets:3,reps:"12-15",req:[],bodyweight:true,why:"La partie basse du grand droit est très difficile à cibler. Cet exercice est l'un des rares à l'isoler.",tips:["Dos collé au sol pendant toute la descente","Jambes légèrement fléchies pour réduire le bras de levier","Descends jusqu'à 5cm du sol sans décoller le dos"],muscles_detail:"Grand droit partie inférieure, psoas-iliaque, transverse de l'abdomen",erreurs:["Dos qui se décolle du sol en descendant — lombaires en danger","Balancement des jambes pour prendre de l'élan","Trop vite — perd le travail excentrique"],conseil:"Si trop difficile au début, fléchis les genoux à 90°. Progresse vers les jambes tendues.",alternatives:["crunch","plank","mountainClimber","russianTwist"]},

russianTwist:{name:"Russian Twist",emoji:"🔄",muscle:"Obliques",muscleGroup:"abs",cat:"bodyweight",tempo:{d:2,h:0,u:2},rest:45,sets:3,reps:"20 (10/côté)",req:[],bodyweight:true,why:"Travaille les deux couches d'obliques simultanément. Excellent pour la stabilité rotatoire du tronc.",tips:["Pieds levés pour plus d'intensité","La rotation vient du buste — pas des épaules","Touche le sol de chaque côté avec contrôle"],muscles_detail:"Obliques externes et internes, transverse de l'abdomen",erreurs:["Rotation des hanches au lieu du buste — perd l'effet","Trop vite sans contrôle — devient un balancement","Dos trop arrondi — lombaires en tension"],conseil:"Ajoute un haltère ou un disque pour progresser. Garde le dos à 45° du sol.",alternatives:["sidePlank","crunch","plank","legRaise"]},

sidePlank:{name:"Gainage latéral",emoji:"⬡",muscle:"Obliques",muscleGroup:"abs",cat:"bodyweight",tempo:{d:0,h:0,u:0},rest:45,sets:3,reps:"30-45 sec/côté",req:[],bodyweight:true,why:"Les obliques et les muscles profonds latéraux en isométrie. Complémentaire au gainage frontal.",tips:["Hanches bien levées — pas qui s'affaissent","Corps en ligne droite de la tête aux pieds","Coude directement sous l'épaule"],muscles_detail:"Obliques externes et internes, carré des lombes, moyen fessier, stabilisateurs de hanche",erreurs:["Hanches qui s'affaissent vers le sol — perd le bénéfice","Corps pas aligné — rotation du tronc","Coude pas sous l'épaule — déséquilibre"],conseil:"Trop facile ? Lève la jambe du dessus ou pose le pied sur une surface instable.",alternatives:["plank","russianTwist","crunch"]},

mountainClimber:{name:"Mountain Climbers",emoji:"🧗",muscle:"Abdos · Cardio",muscleGroup:"abs",cat:"bodyweight",tempo:{d:0,h:0,u:0},rest:30,sets:3,reps:"30 sec",req:[],bodyweight:true,why:"Gainage dynamique combiné au cardio. Brûle des calories tout en renforçant le core profond.",tips:["Hanches stables — ne montent pas et ne bougent pas","Vitesse modérée et contrôlée","Corps en position de pompe rigide"],muscles_detail:"Transverse de l'abdomen, grand droit, fléchisseurs de hanche, épaules, quadriceps",erreurs:["Hanches qui montent trop haut — perd le gainage","Trop vite sans contrôle des hanches","Corps pas rigide — hanches qui bougent latéralement"],conseil:"Commence lentement pour maîtriser la stabilité des hanches avant d'augmenter la vitesse.",alternatives:["plank","crunch","legRaise"]},

hollowBody:{name:"Hollow Body Hold",emoji:"🌙",muscle:"Transverse · Grand droit",muscleGroup:"abs",cat:"bodyweight",tempo:{d:0,h:0,u:0},rest:45,sets:3,reps:"20-30 sec",req:[],bodyweight:true,why:"Position isométrique avancée. Base de la gymnastique qui renforce profondément tout le core.",tips:["Bas du dos collé au sol — priorité absolue","Bras tendus derrière la tête","Jambes jointes et tendues, légèrement levées"],muscles_detail:"Transverse de l'abdomen, grand droit entier, fléchisseurs de hanche",erreurs:["Bas du dos qui décolle du sol — perd l'efficacité","Retenir la respiration — contre-productif","Genoux fléchis quand trop difficile — ok pour débuter"],conseil:"Si trop difficile, fléchis les genoux ou garde les bras le long du corps. Progresse graduellement.",alternatives:["plank","crunch","legRaise"]},
};

export const GENDERS = [
{id:"male",emoji:"👨",label:"Homme",desc:"Force, volume, performance"},
{id:"female",emoji:"👩",label:"Femme",desc:"Galbe, tonicité, bien-être"},
{id:"teen",emoji:"🧒",label:"Moins de 18 ans",desc:"Programme sécurisé et progressif"},
];
export const GOALS = [
{id:"mass",emoji:"💪",label:"Prise de masse",color:"#C8FF00",desc:"Gagner du muscle et du volume"},
{id:"cut",emoji:"🔥",label:"Sèche",color:"#FF4040",desc:"Perdre du gras, garder le muscle"},
{id:"force",emoji:"⚡",label:"Force pure",color:"#FF8C00",desc:"Soulever plus lourd, devenir plus fort"},
{id:"fit",emoji:"🏃",label:"Remise en forme",color:"#3B9EFF",desc:"Retrouver la forme et l'énergie"},
];
export const FEMALE_GOALS = [
{id:"tone",emoji:"✨",label:"Tonicité globale",color:"#A855F7",desc:"Corps ferme et dessiné"},
{id:"cut",emoji:"🔥",label:"Perte de poids",color:"#FF4040",desc:"Affiner et sculpter"},
{id:"fit",emoji:"🏃",label:"Remise en forme",color:"#3B9EFF",desc:"Énergie et santé"},
{id:"mass",emoji:"💪",label:"Prise de muscle",color:"#C8FF00",desc:"Développer progressivement"},
];
export const TEEN_GOALS = [
{id:"fit",emoji:"🏃",label:"Remise en forme",color:"#14B8A6",desc:"Énergie et santé"},
{id:"tone",emoji:"✨",label:"Tonicité",color:"#A855F7",desc:"Corps athlétique"},
{id:"mass",emoji:"💪",label:"Prise de muscle",color:"#C8FF00",desc:"Développer progressivement"},
];
export const LEVELS = [
{id:"beginner",emoji:"🌱",label:"Débutant",desc:"Moins d'1 an"},
{id:"intermediate",emoji:"⚡",label:"Intermédiaire",desc:"1 à 3 ans"},
{id:"advanced",emoji:"🔥",label:"Avancé",desc:"Plus de 3 ans"},
];
export const FREQS = [
{id:3,label:"3 jours",badge:"Minimum",color:"#FF8C00"},
{id:4,label:"4 jours",badge:"Idéal",color:"#C8FF00"},
{id:5,label:"5 jours",badge:"Intensif",color:"#3B9EFF"},
{id:6,label:"6 jours",badge:"Hardcore",color:"#FF4040"},
];
export const ENVS = [
{id:"gym",emoji:"🏋️",label:"Salle de sport"},
{id:"home",emoji:"🏠",label:"À la maison"},
{id:"outdoor",emoji:"🌳",label:"Dehors / Calisthenics"},
{id:"mixed",emoji:"🔀",label:"Variable"},
];
export const EQUIPMENTS = [
{id:"barbell",emoji:"🏋️",label:"Barre + disques"},
{id:"dumbbell",emoji:"🏅",label:"Haltères"},
{id:"pullupbar",emoji:"🎯",label:"Barre de traction"},
{id:"bench",emoji:"🛋️",label:"Banc"},
{id:"cables",emoji:"🔗",label:"Poulies"},
{id:"machines",emoji:"⚙️",label:"Machines"},
{id:"dip_bar",emoji:"🔱",label:"Barres dips"},
{id:"nothing",emoji:"🤲",label:"Poids du corps"},
];

export const RANGS = [
{id:"bronze",nom:"Bronze",couleur:"#CD7F32",emoji:"🥉",grad:"135deg,#3D2B1F,#8B5E3C",xpDiv:[0,80,100,130,160]},
{id:"argent",nom:"Argent",couleur:"#C0C0C0",emoji:"🥈",grad:"135deg,#2A2A2A,#777",xpDiv:[250,300,360,420,500]},
{id:"or",nom:"Or",couleur:"#FFD700",emoji:"🥇",grad:"135deg,#3D3000,#AA8800",xpDiv:[600,720,840,960,1100]},
{id:"platine",nom:"Platine",couleur:"#00D4FF",emoji:"💎",grad:"135deg,#00203D,#007799",xpDiv:[1400,1600,1800,2000,2200]},
{id:"diamant",nom:"Diamant",couleur:"#BF5AF2",emoji:"💠",grad:"135deg,#1A0033,#6600CC",xpDiv:[2800,3200,3600,4000,4500]},
{id:"maitre",nom:"Maître",couleur:"#FF7700",emoji:"🔥",grad:"135deg,#3D1500,#CC5500",xpDiv:[5500,6500,7500,8500,10000]},
{id:"challenger",nom:"Challenger",couleur:"#00FFD1",emoji:"⚡",grad:"135deg,#003D33,#00AAAA",xpDiv:[12000,14000,16000,18000,20000]},
{id:"legende",nom:"Légende",couleur:"#FFD700",emoji:"👑",grad:"135deg,#2A1A00,#997700",xpDiv:[25000,30000,36000,42000,99999]},
];
export const ROMS = ["I","II","III","IV","V"];

export const ACHIEVEMENTS = [
{id:"first_session",name:"Premier pas",desc:"1ère séance complétée",icon:"🌱",xp:50},
{id:"streak_3",name:"3 jours d'affilée",desc:"3 jours consécutifs",icon:"🔥",xp:75},
{id:"streak_7",name:"Semaine parfaite",desc:"7 jours consécutifs",icon:"💫",xp:200},
{id:"sessions_10",name:"Habitude formée",desc:"10 séances au total",icon:"⚡",xp:100},
{id:"sessions_50",name:"Vétéran",desc:"50 séances au total",icon:"🏆",xp:500},
{id:"first_record",name:"Premier record",desc:"Bats ton premier record",icon:"📈",xp:75},
{id:"records_5",name:"Machine de progrès",desc:"5 exercices en record",icon:"🎯",xp:200},
{id:"bench_100",name:"Club des 100kg",desc:"100kg au développé couché",icon:"💪",xp:300},
{id:"squat_100",name:"Squat 100kg",desc:"100kg au squat barre",icon:"🦵",xp:300},
{id:"volume_10t",name:"10 Tonnes",desc:"10 tonnes de volume total",icon:"🏋️",xp:400},
];

export const WEEKLY = [
{id:"w1",name:"5 séances cette semaine",icon:"📅",xp:150,target:5,type:"sessions"},
{id:"w2",name:"Bat 3 records",icon:"📈",xp:200,target:3,type:"records"},
{id:"w3",name:"Volume > 5 tonnes",icon:"🏋️",xp:175,target:5000,type:"volume"},
{id:"w4",name:"Séance > 60 min",icon:"⏱",xp:100,target:3600,type:"duration"},
{id:"w5",name:"3 jours consécutifs",icon:"🔥",xp:125,target:3,type:"streak"},
];
